spring.jpa.hibernate.ddl-auto: none
spring.datasource.url: jdbc:hsqldb:file:addon-db # Use a file-based backing store for HSQL

addon:
  key: cloudTest
  base-url: https://77ca-2402-e280-3e0b-45c-9e0-4b96-7128-5d.ngrok.io

spring:
  thymeleaf: # Thymeleaf
    cache: false
    mode: HTML
    encoding: UTF-8
    prefix: file:src/main/resources/templates/
  resources: # Static resources
    static-locations: file:src/main/resources/static/
    cache:
      period: 0

logging.level.com.atlassian.connect.spring: DEBUG
